# Generated by Django 2.2.10 on 2023-02-13 21:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=100)),
                ('AType', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=100)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(default='profiles/avatar.png', max_length=1000, upload_to='profiles')),
                ('Biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=100)),
                ('Skills', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Rate', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField()),
                ('Status', models.CharField(default='Open', max_length=100)),
                ('Level', models.CharField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=200, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Client')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 15, 47, 366556))),
                ('Target', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(default='profiles/avatar.png', max_length=1000, upload_to='profiles')),
                ('Description', models.TextField(default='None')),
                ('Skills', models.TextField(null=True)),
                ('Profesion', models.TextField(null=True)),
                ('Rate', models.IntegerField(null=True)),
                ('CV', models.FileField(default='cv.default', null=True, upload_to='cvs')),
                ('Availability', models.IntegerField(null=True)),
                ('Biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escrow', models.IntegerField()),
                ('Balance', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(max_length=100)),
                ('Time', models.DateTimeField()),
                ('Type', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Amount', models.IntegerField()),
                ('FreeLancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Writer')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SavedWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 15, 47, 370556))),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Client')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.IntegerField()),
                ('Review', models.TextField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Client')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='Open', max_length=100)),
                ('Body', models.TextField()),
                ('Sent', models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 15, 47, 364556))),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 15, 47, 368556))),
                ('Read', models.BooleanField(default=False)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Chat')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobUnpaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=100)),
                ('Skills', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Rate', models.CharField(max_length=100)),
                ('DateTime', models.DateTimeField()),
                ('Status', models.CharField(default='Open', max_length=100)),
                ('Level', models.CharField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=200, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Client')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Budget', models.IntegerField()),
                ('Escrow', models.IntegerField()),
                ('Time', models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 15, 47, 372532))),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Client')),
                ('Proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Proposal')),
                ('Writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Writer')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='proposals')),
                ('Proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Proposal')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Read', models.BooleanField(default=False)),
                ('Biodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Biodata')),
                ('Notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Notification')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Used', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('Balance', models.IntegerField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Client')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
