# Generated by Django 2.2.10 on 2023-02-13 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 17, 38, 185917)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 17, 38, 182917)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 17, 38, 180917)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 17, 38, 178917)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 17, 38, 184917)),
        ),
    ]
