# Generated by Django 2.2.10 on 2023-02-13 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20230214_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 18, 10, 222451)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 18, 10, 219451)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 18, 10, 217452)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 18, 10, 216452)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 0, 18, 10, 221451)),
        ),
    ]
