# Generated by Django 4.1.2 on 2023-03-22 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20230214_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 22, 41, 40, 510534)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 22, 41, 40, 510534)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 22, 41, 40, 494912)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 22, 41, 40, 494912)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 22, 41, 40, 510534)),
        ),
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=150)),
                ('Department', models.CharField(max_length=30)),
                ('Priority', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.biodata')),
            ],
        ),
    ]
