# Generated by Django 4.1.2 on 2023-03-22 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_hire_time_alter_message_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disputes',
            old_name='closed',
            new_name='Closed',
        ),
        migrations.RenameField(
            model_name='disputes',
            old_name='message',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 23, 22, 23, 412873)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 23, 22, 23, 397078)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 23, 22, 23, 397078)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 23, 22, 23, 397078)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 23, 22, 23, 412873)),
        ),
    ]
