# Generated by Django 4.1.2 on 2023-03-23 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_closed_disputes_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes',
            name='Image',
            field=models.ImageField(max_length=1000, null=True, upload_to='dispute_files'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 22, 30, 11, 55945)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 22, 30, 11, 50947)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 22, 30, 11, 45954)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 22, 30, 11, 40956)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 22, 30, 11, 50947)),
        ),
    ]
