# Generated by Django 4.1.2 on 2023-03-23 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_disputes_image_alter_hire_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputes',
            name='Time_closed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 3, 20, 361199)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 3, 20, 356201)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 3, 20, 351200)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 3, 20, 346201)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 3, 20, 356201)),
        ),
    ]
