# Generated by Django 4.1.2 on 2023-03-23 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_disputes_time_closed_alter_hire_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disputes',
            old_name='Time_closed',
            new_name='Date_filed',
        ),
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 7, 5, 112662)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 7, 5, 107508)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 7, 5, 102508)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 7, 5, 102508)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 24, 0, 7, 5, 112662)),
        ),
    ]
