# Generated by Django 4.1.2 on 2023-03-26 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_rename_time_closed_disputes_date_filed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputes',
            name='Date_filed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='disputes',
            name='Image',
            field=models.ImageField(max_length=1000, null=True, upload_to='dispute'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 10, 23, 13, 214804)),
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 10, 23, 13, 214804)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 10, 23, 13, 204032)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='Sent',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 10, 23, 13, 204032)),
        ),
        migrations.AlterField(
            model_name='savedwriter',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 10, 23, 13, 214804)),
        ),
    ]
